

# 백테스트 기본 공통 설정
common:
  symbol: 'BTCUSDT'
  timeframe: '1d'
  start_date: '2024-07-01'
  end_date: '2025-7-01'
  initial_cash: 1000.0
  commission: 0.0015 # 0.1%

# 1. 단순 백테스트 설정
simple_backtest:
  strategy: 'SmaCrossStrategy'
  params:
    fast_ma: 20
    slow_ma: 50

# 2. 파라미터 최적화 설정
optimization:
  strategy: 'SmaCrossStrategy'
  # 최적화할 파라미터 범위를 지정합니다.
  # Backtrader의 range와 동일하게 (start, stop, step) 형식으로도 사용 가능합니다.
  params_to_optimize:
    fast_ma: [10, 20] # 10, 20을 테스트
    slow_ma: [40, 50, 60] # 40, 50, 60을 테스트 (총 2*3=6회 실행)
  # 최적화 목표 지표 (BacktestEngine의 analyze_results가 반환하는 키값 중 하나)
  optimize_target: 'final_value'

# 3. 워크포워드 분석 설정
walk_forward:
  strategy: 'SmaCrossStrategy'
  # 훈련 기간(In-Sample)과 검증 기간(Out-of-Sample)
  train_period_days: 270 # 약 9개월
  test_period_days: 90   # 약 3개월
  # 워크포워드에서 사용할 최적화 파라미터 (optimization 설정을 재사용할 수도 있음)
  params_to_optimize:
    fast_ma: [10, 20, 30]
    slow_ma: [40, 50, 60]
  optimize_target: 'final_value'

# 결과 저장 경로
results_path:
  base: 'results'
  simple: 'simple'
  optimization: 'optimization'
  walk_forward: 'walk_forward'